# Analitica de Iris

## Imports

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn import datasets
import os

# Carga de Datos

In [8]:
os.listdir('data')

['iris.csv']

In [9]:
columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

In [13]:
df = pd.read_csv('data/iris.csv', names=columns, header=None)

In [14]:
df

     sepal_length  sepal_width  petal_length  petal_width           class
1             5.1          3.5           1.4          0.2     Iris-setosa
2             4.9          3.0           1.4          0.2     Iris-setosa
3             4.7          3.2           1.3          0.2     Iris-setosa
4             4.6          3.1           1.5          0.2     Iris-setosa
5             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
146           6.7          3.0           5.2          2.3  Iris-virginica
147           6.3          2.5           5.0          1.9  Iris-virginica
148           6.5          3.0           5.2          2.0  Iris-virginica
149           6.2          3.4           5.4          2.3  Iris-virginica
150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [24]:
df.tail(5)

     sepal_length  sepal_width  petal_length  petal_width           class
146           6.7          3.0           5.2          2.3  Iris-virginica
147           6.3          2.5           5.0          1.9  Iris-virginica
148           6.5          3.0           5.2          2.0  Iris-virginica
149           6.2          3.4           5.4          2.3  Iris-virginica
150           5.9          3.0           5.1          1.8  Iris-virginica

In [25]:
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width        class
1           5.1          3.5           1.4          0.2  Iris-setosa
2           4.9          3.0           1.4          0.2  Iris-setosa
3           4.7          3.2           1.3          0.2  Iris-setosa
4           4.6          3.1           1.5          0.2  Iris-setosa
5           5.0          3.6           1.4          0.2  Iris-setosa

In [26]:
df.sample(1)

    sepal_length  sepal_width  petal_length  petal_width        class
34           5.5          4.2           1.4          0.2  Iris-setosa